#!/usr/bin/env python

import jsh

def cli_show_str(cli, s):
	print s

def cli_show_random(cli):
	print 'bollox'

cli = jsh.JSH({
	'show': {
		'?': 'Show stuff',
		str: {
			'?': ('string', 'String to show'),
			None: cli_show_str
		},
		'random': {
			'?': 'Show something random',
			None: cli_show_random
		}
	}
})

while True:
	try:
		cli.read_and_execute()
	except jsh.JSHError as err:
		print err
	except EOFError:
		break

